project:
  type: website
  output-dir: docs
  preview:
    watch-inputs: true   # <- recarga al guardar

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Eda
      - href: cnj.qmd
        text: CNJ
      - href: classification.qmd
        text: Classification
      - text: MidTerm
        menu:
          - href: midterm_regression.qmd
            text: Regresión
          - href: midterm_classification.qmd
            text: Clasificación



format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
