project:
  type: website
  output-dir: docs
  preview:
    watch-inputs: true   # <- recarga al guardar

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Eda
      - href: cnj.qmd
        text: CNJ

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
